In [11]:
import pandas as pd
df = pd.read_csv('common_passwords.csv', sep=',')
df['charInLength'] = df['num_chars'] / df['length']
df.groupby('length').mean()

        num_chars  num_digits  num_upper  num_lower  charInLength
length
3        2.000000    1.000000   0.000000   2.000000      0.666667
4        2.895062    1.102469   0.013580   2.881481      0.723765
5        4.786268    0.202658   0.012182   4.774086      0.957254
6        5.312972    0.682935   0.032116   5.280856      0.885495
7        6.621118    0.377188   0.024280   6.596838      0.945874
8        4.172333    3.827667   0.019859   4.152474      0.521542
9        7.205479    1.776256   0.031963   7.173516      0.800609
10       6.202128    3.797872   0.138298   6.063830      0.620213
11       8.607143    2.321429   0.107143   8.500000      0.782468
12       8.857143    3.142857   0.000000   8.857143      0.738095
13      11.500000    1.500000   0.500000  11.000000      0.884615
15      11.000000    4.000000   1.000000  10.000000      0.733333
16      12.000000    4.000000   2.000000  10.000000      0.750000